AllCops:
  Exclude:
    - 'spec/**/*.rb'

LineLength:
  Enabled: false

Documentation:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/FrozenStringLiteralComment:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

Lambda:
  Enabled: false

StringLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

GuardClause:
  Enabled: false

NumericLiterals:
  Enabled: false

MethodLength:
  Max: 20

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Metrics/ParameterLists:
  Max: 7

Naming/UncommunicativeMethodParamName:
  Enabled: false